// Generated by tools/gen-sw.mjs -- do not edit by hand.
//
// Cache-first over a fully precached app. MathBlast has no server side and no
// network calls once it is running, so "offline" is simply its normal state;
// the only thing the network is for is picking up a new version.

const VERSION = 'bca351d0d535';
const CACHE = `mathblast-${VERSION}`;

const ASSETS = [
  "./",
  "./index.html",
  "./src/audio.js",
  "./src/difficulty.js",
  "./src/entities/beasts/arith.js",
  "./src/entities/beasts/base.js",
  "./src/entities/beasts/boss.js",
  "./src/entities/beasts/fracop.js",
  "./src/entities/beasts/fraction.js",
  "./src/entities/beasts/index.js",
  "./src/entities/beasts/integer.js",
  "./src/entities/beasts/mult.js",
  "./src/entities/beasts/percent.js",
  "./src/entities/beasts/power.js",
  "./src/entities/beasts/split.js",
  "./src/entities/beasts/voidling.js",
  "./src/entities/projectile.js",
  "./src/entities/shield.js",
  "./src/fx/camera.js",
  "./src/fx/orbs.js",
  "./src/fx/particles.js",
  "./src/fx/shockwave.js",
  "./src/main.js",
  "./src/problems.js",
  "./src/profiles.js",
  "./src/quality.js",
  "./src/render/post.js",
  "./src/render/starfield.js",
  "./src/theme.js",
  "./src/ui/hud.js",
  "./src/ui/profile.js",
  "./src/ui/touch.js",
  "./src/util.js",
  "./assets/font/jetbrains-mono-latin.woff2",
  "./assets/icons/icon-1024.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/icon-maskable-512.png"
];

self.addEventListener('install', (e) => {
  // A single failed entry rejects addAll and leaves the app with no cache at
  // all, so each asset is fetched on its own and misses are reported.
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const failed = [];
    await Promise.all(ASSETS.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (!res.ok) throw new Error(String(res.status));
        await cache.put(url, res);
      } catch (err) {
        failed.push(`${url}: ${err.message}`);
      }
    }));
    if (failed.length) console.warn('[sw] not cached:', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('mathblast-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      // Only same-origin successes are worth keeping; an opaque or error
      // response cached here would be served forever.
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    } catch {
      // A navigation that misses the cache still has somewhere to go.
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw new Error('offline and not cached: ' + url.pathname);
    }
  })());
});
  