// Regenerates the service worker's precache list and version stamp.
//
//   node tools/gen-sw.mjs
//
// The list is written into sw.js rather than fetched at runtime, because a
// service worker that asks the network what to cache cannot install offline.
// `npm test` asserts the committed list still matches what is on disk, so
// adding a source file without re-running this is a test failure, not a
// silently broken offline build.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;

function walk(dir, out = []) {
  for (const name of readdirSync(join(ROOT, dir)).sort()) {
    const rel = `${dir}/${name}`;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, out);
    else out.push(rel);
  }
  return out;
}

// Everything the game needs with the network switched off. serve.js, the test
// suite and the docs are not part of the shipped app.
export function assets() {
  return [
    './',
    './index.html',
    ...walk('src'),
    ...walk('assets'),
  ].map((p) => (p.startsWith('.') ? p : `./${p}`));
}

export function version(list) {
  const h = createHash('sha256');
  for (const p of list) {
    if (p === './') continue;
    h.update(p);
    h.update(readFileSync(join(ROOT, p.replace(/^\.\//, ''))));
  }
  return h.digest('hex').slice(0, 12);
}

// Importing this module must not rewrite sw.js -- tools/build-www.mjs and the
// test suite both want the asset list without the side effect.
function generate() {
  const list = assets();
  const v = version(list);

  writeFileSync(join(ROOT, 'sw.js'), `// Generated by tools/gen-sw.mjs -- do not edit by hand.
//
// Cache-first over a fully precached app. MathBlast has no server side and no
// network calls once it is running, so "offline" is simply its normal state;
// the only thing the network is for is picking up a new version.

const VERSION = '${v}';
const CACHE = \`mathblast-\${VERSION}\`;

const ASSETS = ${JSON.stringify(list, null, 2).replace(/\n/g, '\n')};

self.addEventListener('install', (e) => {
  // A single failed entry rejects addAll and leaves the app with no cache at
  // all, so each asset is fetched on its own and misses are reported.
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const failed = [];
    await Promise.all(ASSETS.map(async (url) => {
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (!res.ok) throw new Error(String(res.status));
        await cache.put(url, res);
      } catch (err) {
        failed.push(\`\${url}: \${err.message}\`);
      }
    }));
    if (failed.length) console.warn('[sw] not cached:', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('mathblast-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      const res = await fetch(req);
      // Only same-origin successes are worth keeping; an opaque or error
      // response cached here would be served forever.
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    } catch {
      // A navigation that misses the cache still has somewhere to go.
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw new Error('offline and not cached: ' + url.pathname);
    }
  })());
});
  `);

  console.log(`sw.js: ${list.length} assets, version ${v}`);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) generate();
